### ISSUE TITLE
Partial dataset?

### ISSUE THREAD

**Issue by zhibinliao89** [zizhaozhang/nmi-wsi-diagnosis#4]
Dear authors,

Thank you for sharing your work.

Your paper mentioned that there are 620 slides for training, 193+100 for validation and testing.  These match the 620+293 entries in the supplied {train/val_test}_diagnosis.json.

On the other hand, there are only 482 downloadable slides. It is close to 336+142=478 entries in the supplied {train/val_test}_diagnosis_partial.json (used by anno_parser/gen_patches.py).

My questions are:
1) is there a standalone test_diagnosis.json that can be shared or do you recommend just using val+test for testing?
2) can you please include those missing slides in your repo?

Thank you!

**Comment by zizhaozhang** [comment]
Thanks for your questions.
As we have noted in the readme.md of the dataset shared drive, we need get "the permission of UF to release UF Health Shands Hospital data. The whole slides in the folder of Slide/Img/ only contain TCGA data." We can not estimate how long would that take. 

The json file selected_diagnosis_for_comparsion_100.json contains the standalone test set.

**Comment by zhibinliao89** [comment]
Thanks for your reply and looking forward to your entire dataset. Currently, it only has like 10 cases in the selected_diagnosis_for_comparsion_100_partial.json.

P.S. It would be great if you can add that readme.md of the dataset in this repo as well, your dropbox link isn't accessible anymore. Thanks again.
