### ISSUE TITLE
Data set is missing……

### ISSUE THREAD

**Issue by puzhou-wrj** [zizhaozhang/nmi-wsi-diagnosis#5]
dear sir, I have download the data set from https://docs.google.com/forms/d/e/1FAIpQLSfaBugmwdR_BalbwrhkHK64xysaXjiE_JLjOKQVlci2DVTvNg/viewform?usp=sf_link
I find that in the the folder “slide”，in val_test_diagnosis.json，you mentioned picture like“1153831，...，118633”, but in "Slide\Img", I couldn't find picture like“1153831，...，118633”，Is the data set not uploaded completely? thank you

**Comment by zizhaozhang** [comment]
Hi due to data copyright issued we can not resolve, that part of data can not be released at this momentum.
